packages:
  - packages/*
  - packages/reactors/*
  - packages/events/tests/playwright/server

catalog:
  '@ai-sdk/openai': ^2.0.68
  '@instantdb/admin': ^0.22.57
  '@instantdb/core': ^0.22.44
  '@types/node': ^24.5.0
  '@vercel/sandbox': ^0.0.23
  ai: ^5.0.97
  typescript: ^5.9.2
  zod: ^4.3.6

overrides:
  '@excalidraw/excalidraw': link:../ekairos-drawer/packages/excalidraw
  '@ekairos/sandbox': workspace:*
  'next@15.5.x': 15.5.7
  'react@19.2.0': 19.2.1
  'react-dom@19.2.0': 19.2.1
